[background]
path = "/home/solinaire/.config/.blurred_wallpaper"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Bibata-Modern-Ice"
font_name = "JetBrainsMono Nerd Font Mono"
icon_theme_name = "Adwaita"
theme_name = "Adwaita"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
